/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: BlueMesh (https://sketchfab.com/VapTor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/indominus-rex-4k-textures-free-a262dec5fdd54f838cea83a3ee451e43
Title: Indominus Rex [4k textures] FREE
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import scene from "../../assets/3d/indominus_rex_4k_textures_free.glb";

const Trex = ({currentAnimation, ...props}) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF( scene );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    Object.values(actions).forEach((action) => action.stop());

    if (actions[currentAnimation]) {
      actions[currentAnimation].play();
    }
  }, [actions, currentAnimation]);


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.477}
        >
          <group name="Root">
            <group name="Hemi" position={[-0.1, -3.237, 1.892]}>
              <group name="Hemi_1" />
            </group>
            <group
              name="Circle010"
              position={[-0.397, -1.927, -0.254]}
              rotation={[2.438, 0.016, 3.125]}
              scale={0.174}
            >
              <mesh
                name="Circle010_0"
                castShadow
                receiveShadow
                geometry={nodes.Circle010_0.geometry}
                material={materials["Material.001"]}
              />
            </group>
            <group
              name="Circle009"
              position={[0.39, -1.398, 0.154]}
              rotation={[-2.792, 0.016, 3.125]}
              scale={0.174}
            >
              <mesh
                name="Circle009_0"
                castShadow
                receiveShadow
                geometry={nodes.Circle009_0.geometry}
                material={materials["Material.001"]}
              />
            </group>
            <group
              name="Circle008"
              position={[0.064, -2.603, 1.109]}
              rotation={[0.067, 0, 0]}
              scale={0.174}
            >
              <mesh
                name="Circle008_0"
                castShadow
                receiveShadow
                geometry={nodes.Circle008_0.geometry}
                material={materials["Material.001"]}
              />
            </group>
            <group
              name="Circle007"
              position={[0.069, -2.468, 0.974]}
              rotation={[0.067, 0, 0]}
              scale={0.174}
            >
              <mesh
                name="Circle007_0"
                castShadow
                receiveShadow
                geometry={nodes.Circle007_0.geometry}
                material={materials["Material.001"]}
              />
            </group>
            <group
              name="Circle005"
              position={[0, -2.411, 0.917]}
              rotation={[0.067, 0, 0]}
              scale={0.174}
            >
              <mesh
                name="Circle005_0"
                castShadow
                receiveShadow
                geometry={nodes.Circle005_0.geometry}
                material={materials["Material.001"]}
              />
            </group>
            <group
              name="Circle004"
              position={[0, -2.489, 1.055]}
              rotation={[-0.095, 0, 0]}
              scale={0.226}
            >
              <mesh
                name="Circle004_0"
                castShadow
                receiveShadow
                geometry={nodes.Circle004_0.geometry}
                material={materials["Material.001"]}
              />
            </group>
            <group
              name="Circle003"
              position={[0, -2.892, 1.401]}
              rotation={[-0.136, 0, 0]}
              scale={0.226}
            >
              <mesh
                name="Circle003_0"
                castShadow
                receiveShadow
                geometry={nodes.Circle003_0.geometry}
                material={materials["Material.001"]}
              />
            </group>
            <group name="Circle002" position={[0, -2.722, 1.317]} scale={0.226}>
              <mesh
                name="Circle002_0"
                castShadow
                receiveShadow
                geometry={nodes.Circle002_0.geometry}
                material={materials["Material.001"]}
              />
            </group>
            <group name="Armature" position={[0, 0.011, 0.755]}>
              <primitive object={nodes.Armature_rootJoint} />
              <skinnedMesh
                name="BODY_0"
                geometry={nodes.BODY_0.geometry}
                material={materials["Material.001"]}
                skeleton={nodes.BODY_0.skeleton}
              />
              <skinnedMesh
                name="Circle_0"
                geometry={nodes.Circle_0.geometry}
                material={materials["Material.001"]}
                skeleton={nodes.Circle_0.skeleton}
              />
              <skinnedMesh
                name="Circle006_0"
                geometry={nodes.Circle006_0.geometry}
                material={materials["Material.001"]}
                skeleton={nodes.Circle006_0.skeleton}
              />
              <skinnedMesh
                name="Circle027_0"
                geometry={nodes.Circle027_0.geometry}
                material={materials["Material.001"]}
                skeleton={nodes.Circle027_0.skeleton}
              />
              <skinnedMesh
                name="Eye_0"
                geometry={nodes.Eye_0.geometry}
                material={materials["Material.001"]}
                skeleton={nodes.Eye_0.skeleton}
              />
              <group name="BODY" position={[0, -0.011, -0.755]} />
              <group
                name="Circle"
                position={[0, -2.87, 0.197]}
                rotation={[1.222, 0, 0]}
                scale={[0.168, 0.111, 0.168]}
              />
              <group
                name="Circle006"
                position={[0.016, -4.016, 0.269]}
                rotation={[-0.141, 0.035, 0.002]}
                scale={[0.024, 0.031, 0.033]}
              />
              <group
                name="Circle027"
                position={[0.13, -3.311, 0.163]}
                rotation={[-2.329, 0.015, -3.137]}
                scale={[0.015, 0.013, 0.017]}
              />
              <group
                name="Eye"
                position={[0.116, -3.385, 0.577]}
                rotation={[0.182, -0.015, -0.082]}
                scale={[0.056, 0.056, 0.046]}
              />
            </group>
            <group
              name="Lamp"
              position={[4.076, 1.005, 5.904]}
              rotation={[-0.268, 0.602, 1.931]}
            >
              <group name="Lamp_1" />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

export default Trex